# Generated by Django 4.1.2 on 2022-10-14 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id_doctor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_doctor', models.CharField(max_length=50)),
                ('apellido_doctor', models.CharField(max_length=50)),
                ('especialidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_paciente', models.CharField(max_length=50)),
                ('apellido_paciente', models.CharField(max_length=50)),
                ('fecha_Nac', models.DateField(max_length=50)),
                ('direccion_paciente', models.CharField(max_length=50)),
                ('telefono_paciente', models.IntegerField(max_length=50)),
            ],
        ),
    ]
